# Generated by Django 2.2.1 on 2020-01-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_ngo_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ngo_name',
            new_name='ngoname',
        ),
    ]
