# Generated by Django 2.2.1 on 2020-01-23 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200119_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ngoname',
        ),
    ]
